---
 - name: Get deb Vector
   ansible.builtin.get_url:
     url: "https://packages.timber.io/vector/{{ vector_ver }}/vector_{{ vector_ver }}-1_amd64.deb"
     dest: "./vector_{{ vector_ver }}-1_amd64.deb"
 - name: Install deb vector
   become: true
   ansible.builtin.dnf:
     name:
      - vector_{{ vector_ver }}-1_amd64.deb
 - name: Input config Vector
   template:
     src: vector.j2
     dest: /etc/vector/vector.toml
     mode: "0644"